# Generated by Django 5.1.7 on 2025-10-04 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Имя')),
                ('surname', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=32, null=True, verbose_name='Отчество')),
                ('date_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('date_death', models.DateField(blank=True, null=True, verbose_name='Дата смерти')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Биография')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='authur',
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='books.genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Год издания'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='books.author'),
        ),
        migrations.DeleteModel(
            name='Authur',
        ),
    ]
