from repositories.author_repository import AuthorRepository
from repositories.base_repository import BaseRepository
from repositories.user_repository import UserRepository
from repositories.genre_repository import GenreRepository
from repositories.book_repository import BookRepository
from repositories.feed_repository import FeedRepository
from repositories.review_repository import ReviewRepository
from repositories.like_repository import LikeRepository
