"""create Book, Author and Review tables

Revision ID: 7bc8e4d5f0c7
Revises: 783b0a448232
Create Date: 2025-11-11 08:16:14.602831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bc8e4d5f0c7'
down_revision: Union[str, Sequence[str], None] = '783b0a448232'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
