"""rename to tg_id in user model

Revision ID: 8743218dab53
Revises: 2ea2fb876eb7
Create Date: 2025-08-30 13:23:50.630407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8743218dab53'
down_revision: Union[str, Sequence[str], None] = '2ea2fb876eb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tg_id', sa.BigInteger(), nullable=False))
    op.drop_column('users', 'tg_username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tg_username', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_column('users', 'tg_id')
    # ### end Alembic commands ###
